/*
 * blog-pdf.js
 * Adds the "Download PDF" behavior to the button rendered on every
 * blog/<slug>.html page (see Social_bot.py's _render_post_page). The
 * button itself is always visible and always clickable — the gate lives
 * in what happens on click, not in whether the button shows up:
 *
 *   - Basic / Pro / Premium / Trial (same tiers as the article paywall):
 *     generates a PDF of the article client-side (jsPDF + html2canvas)
 *     and downloads it.
 *   - Free / signed-out: shows a small popover pointing at sign-in or
 *     the pricing page instead of producing a file.
 *
 * Every generated PDF gets, on EVERY page: a SaPEX NEXUS header lockup,
 * a large low-opacity SaPEX logo watermark, and the same AI-predictions
 * disclaimer that's already hardcoded onto the article page itself. This
 * is done as a second pass over the finished PDF (decoratePage, below)
 * rather than baked into the article's HTML before rendering, because
 * jsPDF's html() pagination only knows the final page count once the
 * content has already been laid out.
 *
 * Depends on:
 *   - jsPDF + html2canvas, loaded via <script> tags before this file.
 *   - window.SAPEX_VIEWER_PLAN, window.SAPEX_VIEWER_LOGGED_IN and
 *     window.SAPEX_SIGN_IN, all published by blog-enhance.js. If that
 *     script hasn't run yet (or failed), these default to
 *     free/signed-out — never to "let a free visitor through".
 */
(function () {
    const PAID_TIERS = ['basic', 'pro', 'premium', 'trial'];
    const LOGO_URL = '/Assets/sapex-icon.png';
    const BRAND_TEXT = 'SaPEX NEXUS';
    const DISCLAIMER_TEXT = 'These are predictions generated by SaPEX_001 Alpha Model, a new and actively-training model, based on publicly available information about the parties involved. They do not constitute financial, investment, or legal advice and should not be relied upon for real-world decisions of any kind. For educational purposes only.';

    let logoDataUrlPromise = null;
    function loadLogo() {
        if (!logoDataUrlPromise) {
            logoDataUrlPromise = fetch(LOGO_URL)
                .then((r) => {
                    if (!r.ok) throw new Error('logo fetch failed: ' + r.status);
                    return r.blob();
                })
                .then((blob) => new Promise((resolve, reject) => {
                    const reader = new FileReader();
                    reader.onload = () => resolve(reader.result);
                    reader.onerror = reject;
                    reader.readAsDataURL(blob);
                }))
                .catch((e) => {
                    // Non-fatal — the PDF still generates, just without the
                    // header icon / watermark image.
                    console.warn('blog-pdf.js: could not load logo, PDF will skip the watermark.', e);
                    return null;
                });
        }
        return logoDataUrlPromise;
    }

    // blog-enhance.js sets these after its own async Supabase auth/plan
    // check finishes. Same 2.5s fallback window blog-ads.js already uses
    // for the same globals, so a slow lookup blocks the export rather than
    // silently treating a free visitor as paid.
    function waitForPlan() {
        return new Promise((resolve) => {
            const start = Date.now();
            (function poll() {
                if (typeof window.SAPEX_VIEWER_PLAN !== 'undefined' || Date.now() - start > 2500) {
                    resolve({
                        plan: window.SAPEX_VIEWER_PLAN || 'free',
                        loggedIn: !!window.SAPEX_VIEWER_LOGGED_IN,
                    });
                } else {
                    setTimeout(poll, 100);
                }
            })();
        });
    }

    function closePopover() {
        const existing = document.getElementById('blog-pdf-popover');
        if (existing) existing.remove();
    }

    function showUpsellPopover(anchorBtn, loggedIn) {
        closePopover();
        const pop = document.createElement('div');
        pop.id = 'blog-pdf-popover';
        pop.className = 'blog-pdf-popover';
        const ctaHtml = loggedIn
            ? '<a href="../app.html#pricing" class="blog-pdf-popover__btn">Upgrade <i class="fa-solid fa-crown"></i></a>'
            : '<button type="button" class="blog-pdf-popover__btn" id="blog-pdf-popover-signin">Sign In <i class="fa-solid fa-arrow-right"></i></button>';
        pop.innerHTML = '<p>PDF export is available for Basic, Pro, Premium, and Trial members.</p>' + ctaHtml;
        anchorBtn.insertAdjacentElement('afterend', pop);

        const signinBtn = pop.querySelector('#blog-pdf-popover-signin');
        if (signinBtn) {
            signinBtn.addEventListener('click', function () {
                if (typeof window.SAPEX_SIGN_IN === 'function') window.SAPEX_SIGN_IN();
            });
        }
        // Dismiss on outside click. Deferred one tick so the click that
        // opened the popover doesn't immediately close it.
        setTimeout(function () {
            document.addEventListener('click', function onDocClick(e) {
                if (!pop.contains(e.target) && e.target !== anchorBtn) {
                    closePopover();
                    document.removeEventListener('click', onDocClick);
                }
            });
        }, 0);
    }

    // Stamps the header, watermark and disclaimer onto whichever page of
    // `doc` is currently selected (doc.setPage must be called first).
    // Drawn AFTER the article content, so opacity is kept low enough that
    // the watermark reads as background rather than covering the text.
    function decoratePage(doc, logo, pageWidth, pageHeight) {
        // Header lockup
        if (logo) {
            try { doc.addImage(logo, 'PNG', 40, 24, 26, 26); } catch (e) { /* skip image, keep going */ }
        }
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.setTextColor(20, 24, 32);
        doc.text(BRAND_TEXT, logo ? 74 : 40, 42);
        doc.setDrawColor(220, 224, 230);
        doc.line(40, 58, pageWidth - 40, 58);

        // Big centered watermark
        if (logo) {
            const size = Math.min(pageWidth, pageHeight) * 0.55;
            try {
                doc.saveGraphicsState();
                doc.setGState(new doc.GState({ opacity: 0.06 }));
                doc.addImage(logo, 'PNG', (pageWidth - size) / 2, (pageHeight - size) / 2, size, size);
                doc.restoreGraphicsState();
            } catch (e) { /* skip watermark, keep going */ }
        }

        // Disclaimer footer, repeated on every page
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(120, 128, 140);
        const lines = doc.splitTextToSize(DISCLAIMER_TEXT, pageWidth - 80);
        doc.text(lines, 40, pageHeight - 22 - (lines.length - 1) * 8);
    }

    // Builds an off-DOM copy of the article (title, meta, body) for
    // html2canvas to rasterize. Reaching this function already required an
    // active paid plan (see the click handler below), so the clone is
    // always unlocked regardless of this visitor's own on-page paywall
    // state — there's nothing left to gate at this point.
    function buildPrintClone() {
        const article = document.querySelector('.blog-post');
        const title = article ? article.querySelector('h1') : null;
        const meta = article ? article.querySelector('.blog-card__meta') : null;
        const body = document.querySelector('.blog-post__body');
        if (!body) return null;

        const wrap = document.createElement('div');
        wrap.style.cssText = 'width:680px; padding:0; font-family:Georgia,serif; color:#1a1f28; background:#ffffff;';

        if (title) {
            const h1 = title.cloneNode(true);
            h1.style.cssText = 'font-size:24px; line-height:1.3; margin:0 0 8px; color:#101418;';
            wrap.appendChild(h1);
        }
        if (meta) {
            const m = meta.cloneNode(true);
            m.style.cssText = 'font-size:11px; color:#6b7280; margin:0 0 20px; display:flex; gap:10px; flex-wrap:wrap;';
            wrap.appendChild(m);
        }
        const bodyClone = body.cloneNode(true);
        bodyClone.classList.add('paywall-unlocked');
        bodyClone.style.cssText = 'font-size:13px; line-height:1.7; color:#232a35;';
        wrap.appendChild(bodyClone);
        return wrap;
    }

    function generatePdf(btn) {
        const jspdfNs = window.jspdf;
        if (!jspdfNs || !jspdfNs.jsPDF || typeof window.html2canvas === 'undefined') {
            console.warn('blog-pdf.js: jsPDF/html2canvas failed to load, cannot generate PDF.');
            btn.disabled = false;
            return;
        }
        const { jsPDF } = jspdfNs;

        const clone = buildPrintClone();
        if (!clone) {
            btn.disabled = false;
            return;
        }

        const originalLabel = btn.innerHTML;
        btn.disabled = true;
        btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Preparing…';

        // Rendered off-screen (not display:none — html2canvas can't measure
        // an element that isn't actually laid out).
        clone.style.position = 'fixed';
        clone.style.left = '-10000px';
        clone.style.top = '0';
        document.body.appendChild(clone);

        function cleanup() {
            if (clone.parentNode) document.body.removeChild(clone);
            btn.disabled = false;
            btn.innerHTML = originalLabel;
        }

        loadLogo().then(function (logo) {
            const doc = new jsPDF({ unit: 'pt', format: 'a4' });
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();

            doc.html(clone, {
                margin: [70, 40, 60, 40],
                autoPaging: 'text',
                width: pageWidth - 80,
                windowWidth: 680,
                html2canvas: { scale: 0.75, useCORS: true },
                callback: function (renderedDoc) {
                    try {
                        const pageCount = renderedDoc.internal.getNumberOfPages();
                        for (let i = 1; i <= pageCount; i++) {
                            renderedDoc.setPage(i);
                            decoratePage(renderedDoc, logo, pageWidth, pageHeight);
                        }
                        const slug = btn.dataset.slug || 'article';
                        renderedDoc.save('sapex-nexus-' + slug + '.pdf');
                    } catch (e) {
                        console.warn('blog-pdf.js: failed while finalizing PDF.', e);
                    } finally {
                        cleanup();
                    }
                },
            });
        }).catch(function (e) {
            console.warn('blog-pdf.js: PDF generation failed.', e);
            cleanup();
        });
    }

    function run() {
        const btn = document.getElementById('blog-pdf-btn');
        if (!btn) return;
        btn.addEventListener('click', function () {
            closePopover();
            waitForPlan().then(function (state) {
                if (PAID_TIERS.includes(state.plan)) {
                    generatePdf(btn);
                } else {
                    showUpsellPopover(btn, state.loggedIn);
                }
            });
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', run);
    } else {
        run();
    }
})();